In [17]:
# create an array

import array

my_array = array.array('i', [1,2,3,4])
print(my_array)

# inserting
def insertArray(arr, index, value):
    print(arr.insert(index, value))
        
# traverse the array
def traverseArray(array):
    for i in array:
        print(i)

# accesiong the element of array
   
def accessElement(array, index): 
    if index > len(array):
        print("there is not an element this index")
    else:
        print(array[index])

# searching the element

def searchElement(array, index):
    for i in range(len(array)):
        if array[i] == index:
            return i
    return -1


# delete the element

def deleteEle(array, index):
    array.remove(index)
    print(array)

if __name__ == "__main__":

   insertion = insertArray(arr=my_array, index = 0, value=7)
   print(insertion)

   traverse =  traverseArray(my_array)
   print(traverse)

   access = accessElement(my_array, 4)
   print(access)

   searchEle = searchElement(my_array, 2)
   print(searchEle)

   deleteEle = deleteEle(my_array, 0)
   print(deleteEle)

array('i', [1, 2, 3, 4])
None
None
7
1
2
3
4
None
4
None
2


ValueError: array.remove(x): x not in array

In [7]:
myarr = my_array.insert(0, 7)
print(myarr)

None


In [8]:
my_array

array('i', [7, 7, 1, 2, 3, 4])

In [24]:
from array import *

# 1. Create an array and traverse

my_arr = array('i', [1,2,3,4,5])

for i in my_arr:
    print(i)

# access individual element through indexes
print('step 2')
print(my_arr[3])


# 3. Append any value to the array using append() method

print("step 3")
my_arr.append(6)
print(my_arr)

# 4. Insert value in array using insert() method
print("Step 4")
my_arr.insert(0, 23)
print(my_arr)

# 5. extend method python array using extend() method

print("step 5")

my_array1 = array('i', [10, 11, 12])
my_arr.extend(my_array1)
print(my_arr)

# 6. Add items from list into array using fromlist() method

print("Step 6")
tempList = [20,21,22]
my_arr.fromlist(tempList)
print(my_arr)

# 7. Remove element any array using remove() method
print("Step 7")
my_arr.remove(11)
print(my_arr)

# remove last element using the pop() method
print("step 8")
my_arr.pop()
print(my_arr)

# 9. Fetch any element through its index using index() method
print('Step 9')
print(my_arr.index(21))

# 10. Reverse a python array using an reverse function
print("Step 10")
my_arr.reverse()
print(my_arr)

# 11. Get array buffer information through buffer_info() method
print("Step 11")
print(my_arr.buffer_info())

# 12. Check for number of occurrences of an element count() method
print("Step 12")
my_arr.append(11)
print(my_arr.count(11))
print(my_arr)

# 13. converting the array to string using string method
print("Step 13")
strTemp = str(my_arr)
print(strTemp)
type(strTemp)


# convert array to list using tolist() method
print("Step 14")
# print(my_arr.tolist())

# 15. Append a string to char array using fromstring() method

# 16. Slice Elements from an array
print("Step 16")
my_arr[1:4]

1
2
3
4
5
step 2
4
step 3
array('i', [1, 2, 3, 4, 5, 6])
Step 4
array('i', [23, 1, 2, 3, 4, 5, 6])
step 5
array('i', [23, 1, 2, 3, 4, 5, 6, 10, 11, 12])
Step 6
array('i', [23, 1, 2, 3, 4, 5, 6, 10, 11, 12, 20, 21, 22])
Step 7
array('i', [23, 1, 2, 3, 4, 5, 6, 10, 12, 20, 21, 22])
step 8
array('i', [23, 1, 2, 3, 4, 5, 6, 10, 12, 20, 21])
Step 9
10
Step 10
array('i', [21, 20, 12, 10, 6, 5, 4, 3, 2, 1, 23])
Step 11
(140427644456304, 11)
Step 12
1
array('i', [21, 20, 12, 10, 6, 5, 4, 3, 2, 1, 23, 11])
Step 13
array('i', [21, 20, 12, 10, 6, 5, 4, 3, 2, 1, 23, 11])
Step 14
Step 16


array('i', [20, 12, 10])

### Lets Create Two Diamensional array

In [16]:
import numpy as np

twoDArray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9]])

print(twoDArray)

# so the time complexity and space complexity is o(mn)

# create newTwo D array

# newTwoDArray = np.insert(twoDArray, 1, [[1,2,3,4]], axis=0)
# print(newTwoDArray)

newTwoDArray = np.append(twoDArray, [[1,2,3,4]], axis=0)
print(newTwoDArray)


def accessElements(array, rowIndex, colIndex):
    if rowIndex >= len(array) and colIndex >= len(array[0]):
        print('incorrect index')
    else:
       print(array[rowIndex][colIndex])

# accessElements(twoDArray, 2, 3)


# traverse 2d array

def traverseTDArray(array):
    for i in range(len(array)):
        for j in range(len(array[0])):
            print(array[i][j])

# traverseTDArray(twoDArray)

# searching the element in twoD array

def searchTDArray(array, value):
    for i in range(len(array)):
        for j in range(len(array)):
            if array[i][j] == value:
                return 'The value is located at index ' + str(i) + "" + str(j)
            
    return 'The element is not found'

searchTDArray(twoDArray, 14)

print("Deleted array")
newTwoDArray = np.delete(twoDArray, 1, axis=1)
print(newTwoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]
 [ 1  2  3  4]]
Deleted array
[[11 10  6]
 [10 11  5]
 [12 12  8]
 [15 14  9]]
